// This file is @generated by prost-build.
/// Registration — sent by agent on first connect (before Yamux negotiation)
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WraithRegistration {
    #[prost(string, tag = "1")]
    pub hostname: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub username: ::prost::alloc::string::String,
    /// "linux", "windows", "macos", "bsd"
    #[prost(string, tag = "3")]
    pub os: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub os_version: ::prost::alloc::string::String,
    /// "x64", "x86", "arm", etc.
    #[prost(string, tag = "5")]
    pub arch: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub domain: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub ip_address: ::prost::alloc::string::String,
    #[prost(uint32, tag = "8")]
    pub pid: u32,
    /// agent has root (real TUN support)
    #[prost(bool, tag = "9")]
    pub tun_capable: bool,
    /// agent using custom userspace stack
    #[prost(bool, tag = "10")]
    pub userspace_tun: bool,
    #[prost(bool, tag = "11")]
    pub supports_tls: bool,
    #[prost(bool, tag = "12")]
    pub supports_aes256: bool,
}
/// Heartbeat — periodic check-in from agent
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WraithHeartbeat {
    #[prost(uint32, tag = "1")]
    pub commands_executed: u32,
    #[prost(string, tag = "2")]
    pub status: ::prost::alloc::string::String,
    #[prost(uint64, tag = "3")]
    pub timestamp: u64,
}
/// CommandResult — response to a command
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WraithCommandResult {
    #[prost(string, tag = "1")]
    pub command_id: ::prost::alloc::string::String,
    /// "success" | "error" | "timeout"
    #[prost(string, tag = "2")]
    pub status: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub stdout: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub stderr: ::prost::alloc::string::String,
    #[prost(uint32, tag = "5")]
    pub exit_code: u32,
    #[prost(string, tag = "6")]
    pub error: ::prost::alloc::string::String,
    #[prost(uint64, tag = "7")]
    pub duration_ms: u64,
}
/// FileTransfer — upload/download data
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WraithFileTransfer {
    /// "upload" | "download"
    #[prost(string, tag = "1")]
    pub action: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub remote_path: ::prost::alloc::string::String,
    #[prost(uint64, tag = "3")]
    pub offset: u64,
    #[prost(uint64, tag = "4")]
    pub total_size: u64,
    #[prost(bytes = "vec", tag = "5")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
/// NexusCommand — sent by Nexus to agent via control channel
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NexusCommand {
    #[prost(string, tag = "1")]
    pub command_id: ::prost::alloc::string::String,
    /// "execute", "upload", "download", "add_relay", etc.
    #[prost(string, tag = "2")]
    pub action: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "3")]
    pub params: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(uint32, tag = "4")]
    pub timeout: u32,
}
/// AddRelay — C2 tells agent to spawn a TCP listener that forwards to connect_addr via relay chain
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddRelay {
    /// "0.0.0.0:8080" — address to listen on
    #[prost(string, tag = "1")]
    pub listen_addr: ::prost::alloc::string::String,
    /// "target:80" — address to connect to through relay chain
    #[prost(string, tag = "2")]
    pub connect_addr: ::prost::alloc::string::String,
    /// unique ID for this relay
    #[prost(string, tag = "3")]
    pub relay_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddRelayResponse {
    #[prost(string, tag = "1")]
    pub relay_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub success: bool,
    #[prost(string, tag = "3")]
    pub error_msg: ::prost::alloc::string::String,
    /// actual address bound
    #[prost(string, tag = "4")]
    pub bound_addr: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TunnelOpen {
    #[prost(string, tag = "1")]
    pub tunnel_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub relay_tun_ip: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub agent_tun_ip: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub tunnel_netmask: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub routes: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub encryption: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "7")]
    pub nonce: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TunnelOpenAck {
    #[prost(string, tag = "1")]
    pub tunnel_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub success: bool,
    #[prost(string, tag = "3")]
    pub error_msg: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub assigned_ip: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TunnelClose {
    #[prost(string, tag = "1")]
    pub tunnel_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TunnelStats {
    #[prost(string, tag = "1")]
    pub tunnel_id: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub bytes_in: u64,
    #[prost(uint64, tag = "3")]
    pub bytes_out: u64,
    #[prost(uint64, tag = "4")]
    pub packets_in: u64,
    #[prost(uint64, tag = "5")]
    pub packets_out: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TunnelStatsRequest {
    #[prost(string, tag = "1")]
    pub tunnel_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TunnelData {
    #[prost(string, tag = "1")]
    pub tunnel_id: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Keepalive {
    #[prost(string, tag = "1")]
    pub tunnel_id: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub timestamp: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct KeepaliveAck {
    #[prost(string, tag = "1")]
    pub tunnel_id: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub timestamp: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RelayOpen {
    #[prost(string, tag = "1")]
    pub relay_id: ::prost::alloc::string::String,
    /// "tcp" | "udp" | "file" | "exec" | "listener" | "forward"
    #[prost(string, tag = "2")]
    pub mode: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub local_addr: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub remote_addr: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub file_path: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub command: ::prost::alloc::string::String,
    #[prost(uint32, tag = "7")]
    pub timeout: u32,
    #[prost(bool, tag = "8")]
    pub keepalive: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RelayOpenAck {
    #[prost(string, tag = "1")]
    pub relay_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub success: bool,
    #[prost(string, tag = "3")]
    pub error_msg: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub bound_addr: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RelayClose {
    #[prost(string, tag = "1")]
    pub relay_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RelayStats {
    #[prost(string, tag = "1")]
    pub relay_id: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub bytes_in: u64,
    #[prost(uint64, tag = "3")]
    pub bytes_out: u64,
    #[prost(uint64, tag = "4")]
    pub connections: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RelayStatsRequest {
    #[prost(string, tag = "1")]
    pub relay_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RelayList {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RelayListResponse {
    #[prost(message, repeated, tag = "1")]
    pub relays: ::prost::alloc::vec::Vec<relay_list_response::RelayInfo>,
}
/// Nested message and enum types in `RelayListResponse`.
pub mod relay_list_response {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct RelayInfo {
        #[prost(string, tag = "1")]
        pub relay_id: ::prost::alloc::string::String,
        #[prost(string, tag = "2")]
        pub mode: ::prost::alloc::string::String,
        #[prost(string, tag = "3")]
        pub local_addr: ::prost::alloc::string::String,
        #[prost(string, tag = "4")]
        pub remote_addr: ::prost::alloc::string::String,
        #[prost(string, tag = "5")]
        pub status: ::prost::alloc::string::String,
        #[prost(uint64, tag = "6")]
        pub connections: u64,
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TunnelControl {
    #[prost(oneof = "tunnel_control::Msg", tags = "1, 2, 3, 4, 5, 6, 7")]
    pub msg: ::core::option::Option<tunnel_control::Msg>,
}
/// Nested message and enum types in `TunnelControl`.
pub mod tunnel_control {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Msg {
        #[prost(message, tag = "1")]
        Open(super::TunnelOpen),
        #[prost(message, tag = "2")]
        OpenAck(super::TunnelOpenAck),
        #[prost(message, tag = "3")]
        Close(super::TunnelClose),
        #[prost(message, tag = "4")]
        Stats(super::TunnelStats),
        #[prost(message, tag = "5")]
        StatsRequest(super::TunnelStatsRequest),
        #[prost(message, tag = "6")]
        Keepalive(super::Keepalive),
        #[prost(message, tag = "7")]
        KeepaliveAck(super::KeepaliveAck),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RelayControl {
    #[prost(oneof = "relay_control::Msg", tags = "1, 2, 3, 4, 5, 6, 7")]
    pub msg: ::core::option::Option<relay_control::Msg>,
}
/// Nested message and enum types in `RelayControl`.
pub mod relay_control {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Msg {
        #[prost(message, tag = "1")]
        Open(super::RelayOpen),
        #[prost(message, tag = "2")]
        OpenAck(super::RelayOpenAck),
        #[prost(message, tag = "3")]
        Close(super::RelayClose),
        #[prost(message, tag = "4")]
        Stats(super::RelayStats),
        #[prost(message, tag = "5")]
        StatsRequest(super::RelayStatsRequest),
        #[prost(message, tag = "6")]
        List(super::RelayList),
        #[prost(message, tag = "7")]
        ListResponse(super::RelayListResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AgentMessage {
    #[prost(oneof = "agent_message::Msg", tags = "1, 2, 3, 4, 5, 6, 7, 8")]
    pub msg: ::core::option::Option<agent_message::Msg>,
}
/// Nested message and enum types in `AgentMessage`.
pub mod agent_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Msg {
        #[prost(message, tag = "1")]
        Registration(super::WraithRegistration),
        #[prost(message, tag = "2")]
        Heartbeat(super::WraithHeartbeat),
        #[prost(message, tag = "3")]
        Result(super::WraithCommandResult),
        #[prost(message, tag = "4")]
        FileTransfer(super::WraithFileTransfer),
        #[prost(message, tag = "5")]
        Command(super::NexusCommand),
        #[prost(message, tag = "6")]
        TunnelControl(super::TunnelControl),
        #[prost(message, tag = "7")]
        RelayControl(super::RelayControl),
        #[prost(message, tag = "8")]
        PeerMessage(super::PeerMessage),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PeerInfo {
    #[prost(string, tag = "1")]
    pub node_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub tun_capable: bool,
    #[prost(string, tag = "4")]
    pub tun_ip: ::prost::alloc::string::String,
    #[prost(bool, tag = "5")]
    pub supports_relay: bool,
    #[prost(bool, tag = "6")]
    pub supports_nexus: bool,
    #[prost(map = "string, string", tag = "7")]
    pub options: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PeerAck {
    #[prost(string, tag = "1")]
    pub node_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub accepted: bool,
    #[prost(string, tag = "3")]
    pub error: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PeerMessage {
    #[prost(oneof = "peer_message::Msg", tags = "1, 2")]
    pub msg: ::core::option::Option<peer_message::Msg>,
}
/// Nested message and enum types in `PeerMessage`.
pub mod peer_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Msg {
        #[prost(message, tag = "1")]
        Info(super::PeerInfo),
        #[prost(message, tag = "2")]
        Ack(super::PeerAck),
    }
}
