// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WraithMessage {
    #[prost(enumeration = "MessageType", tag = "1")]
    pub msg_type: i32,
    #[prost(string, tag = "2")]
    pub message_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub timestamp: i64,
    /// routing target for agent chain
    #[prost(string, tag = "16")]
    pub target_wraith_id: ::prost::alloc::string::String,
    #[prost(
        oneof = "wraith_message::Payload",
        tags = "4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15"
    )]
    pub payload: ::core::option::Option<wraith_message::Payload>,
}
/// Nested message and enum types in `WraithMessage`.
pub mod wraith_message {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "4")]
        Registration(super::Registration),
        #[prost(message, tag = "5")]
        Heartbeat(super::Heartbeat),
        #[prost(message, tag = "6")]
        Command(super::Command),
        #[prost(message, tag = "7")]
        Result(super::CommandResult),
        #[prost(message, tag = "8")]
        RelayCreate(super::RelayCreate),
        #[prost(message, tag = "9")]
        RelayDelete(super::RelayDelete),
        #[prost(message, tag = "10")]
        RelayList(super::RelayList),
        #[prost(message, tag = "11")]
        RelayListResponse(super::RelayListResponse),
        #[prost(message, tag = "12")]
        WraithRegistration(super::WraithRegistration),
        #[prost(message, tag = "13")]
        PeerUpdate(super::PeerUpdate),
        #[prost(message, tag = "14")]
        PeerList(super::PeerList),
        #[prost(message, tag = "15")]
        PeerListResponse(super::PeerListResponse),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Registration {
    #[prost(string, tag = "1")]
    pub hostname: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub os: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub ip_address: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Heartbeat {
    #[prost(int64, tag = "1")]
    pub last_command_time: i64,
    #[prost(string, tag = "2")]
    pub status: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Command {
    #[prost(string, tag = "1")]
    pub command_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub action: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "3")]
    pub params: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(int32, tag = "4")]
    pub timeout: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommandResult {
    #[prost(string, tag = "1")]
    pub command_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub status: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub output: ::prost::alloc::string::String,
    #[prost(int32, tag = "4")]
    pub exit_code: i32,
    #[prost(int64, tag = "5")]
    pub duration_ms: i64,
    #[prost(string, tag = "6")]
    pub error: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RelayEndpoint {
    #[prost(string, tag = "1")]
    pub host: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub port: i32,
    /// "tcp" or "udp"
    #[prost(string, tag = "3")]
    pub protocol: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RelayConfig {
    #[prost(message, optional, tag = "1")]
    pub listen: ::core::option::Option<RelayEndpoint>,
    #[prost(message, optional, tag = "2")]
    pub forward: ::core::option::Option<RelayEndpoint>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RelayCreate {
    #[prost(string, tag = "1")]
    pub relay_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub config: ::core::option::Option<RelayConfig>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RelayDelete {
    #[prost(string, tag = "1")]
    pub relay_id: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RelayList {}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RelayListResponse {
    #[prost(message, repeated, tag = "1")]
    pub relays: ::prost::alloc::vec::Vec<RelayInfo>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RelayInfo {
    #[prost(string, tag = "1")]
    pub relay_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub listen_host: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub listen_port: i32,
    #[prost(string, tag = "4")]
    pub forward_host: ::prost::alloc::string::String,
    #[prost(int32, tag = "5")]
    pub forward_port: i32,
    #[prost(bool, tag = "6")]
    pub active: bool,
}
/// Wraith-to-Wraith Registration
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WraithRegistration {
    #[prost(string, tag = "1")]
    pub wraith_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub hostname: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub os: ::prost::alloc::string::String,
    #[prost(int64, tag = "4")]
    pub connected_at: i64,
}
/// Peer list/management
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PeerInfo {
    #[prost(string, tag = "1")]
    pub wraith_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub hostname: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub connected: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PeerList {}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PeerListResponse {
    #[prost(string, tag = "1")]
    pub wraith_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub peers: ::prost::alloc::vec::Vec<PeerInfo>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PeerUpdate {
    #[prost(string, tag = "1")]
    pub wraith_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub hostname: ::prost::alloc::string::String,
    /// "connected" or "disconnected"
    #[prost(string, tag = "3")]
    pub action: ::prost::alloc::string::String,
    #[prost(int64, tag = "4")]
    pub timestamp: i64,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MessageType {
    Registration = 0,
    Heartbeat = 1,
    Command = 2,
    CommandResult = 3,
    RelayCreate = 4,
    RelayDelete = 5,
    RelayList = 6,
    RelayListResponse = 7,
    WraithRegistration = 8,
    PeerUpdate = 9,
    PeerList = 10,
    PeerListResponse = 11,
}
impl MessageType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            MessageType::Registration => "REGISTRATION",
            MessageType::Heartbeat => "HEARTBEAT",
            MessageType::Command => "COMMAND",
            MessageType::CommandResult => "COMMAND_RESULT",
            MessageType::RelayCreate => "RELAY_CREATE",
            MessageType::RelayDelete => "RELAY_DELETE",
            MessageType::RelayList => "RELAY_LIST",
            MessageType::RelayListResponse => "RELAY_LIST_RESPONSE",
            MessageType::WraithRegistration => "WRAITH_REGISTRATION",
            MessageType::PeerUpdate => "PEER_UPDATE",
            MessageType::PeerList => "PEER_LIST",
            MessageType::PeerListResponse => "PEER_LIST_RESPONSE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "REGISTRATION" => Some(Self::Registration),
            "HEARTBEAT" => Some(Self::Heartbeat),
            "COMMAND" => Some(Self::Command),
            "COMMAND_RESULT" => Some(Self::CommandResult),
            "RELAY_CREATE" => Some(Self::RelayCreate),
            "RELAY_DELETE" => Some(Self::RelayDelete),
            "RELAY_LIST" => Some(Self::RelayList),
            "RELAY_LIST_RESPONSE" => Some(Self::RelayListResponse),
            "WRAITH_REGISTRATION" => Some(Self::WraithRegistration),
            "PEER_UPDATE" => Some(Self::PeerUpdate),
            "PEER_LIST" => Some(Self::PeerList),
            "PEER_LIST_RESPONSE" => Some(Self::PeerListResponse),
            _ => None,
        }
    }
}
